// Generated by the Collection Admin page.
// Upload next to index.html. Delete this file to revert everything.
window.__OVERRIDES = {
 "inv645": {
  "category": "Vintage Computing",
  "sub": "Hardware"
 },
 "inv646": {
  "category": "Electronics"
 },
 "inv647": {
  "category": "Memorabilia"
 }
};
