// Generated by the Collection Admin page.
// Upload next to index.html. Delete this file to revert everything.
window.__OVERRIDES = {
 "inv645": {
  "category": "Vintage Computing",
  "sub": "Hardware"
 },
 "inv646": {
  "category": "Electronics"
 },
 "inv647": {
  "category": "Memorabilia"
 },
 "inv309": {
  "hidden": 1
 },
 "inv255": {
  "hidden": 1
 },
 "inv3": {
  "sub": "Sports"
 }
};
